---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600

  - name: Install needed packages
    apt: pkg={{item}} state=installed
    with_items:
      - build-essential
      - logrotate
      - curl
      - git
      - update-motd
      - unzip

  - name: Check if packages need to be autoremoved
    command: apt-get --dry-run autoremove
    register: check_autoremove
    changed_when: False

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    when: "'packages will be REMOVED' in check_autoremove.stdout"

  - name: Disable periodic OS update checks
    lineinfile: dest=/etc/apt/apt.conf.d/10periodic regexp="^APT::Periodic::Update-Package-Lists \"1\"" line="APT::Periodic::Update-Package-Lists \"0\";" state=present
    ignore_errors: true

  - name: Create the deploy user
    user: name={{user}} comment="deploy user" generate_ssh_key=yes ssh_key_bits=2048 state=present shell=/bin/bash password="$6$RlaEIfWR14KY$WoNo3mIglK7Wl7YTNIbcPlwE4zIvb1VlIQO60Otc4wFCly07xHpmwTZFkOFofzY2AHbpa5m1vYc/12jBgDrXC0" groups="sudo,dialout,audio,adm,www-data,plugdev"

  - name: Set {{user}} as sudoer
    lineinfile: "dest=/etc/sudoers line='{{user}} ALL=(ALL) NOPASSWD : ALL'"

  - name: FW Allow everything
    ufw: state=enabled policy=allow

  - name: Allow ForwardAgent to work despite Sudo
    lineinfile: "dest=/etc/sudoers line='Defaults    env_keep += \"SSH_AUTH_SOCK\"'"

  - name: Add SSH-Agent to bashrc
    lineinfile: dest={{home}}/.bashrc line='if [ -z "$SSH_AUTH_SOCK" ] ; then eval `ssh-agent -s` &> /dev/null; ssh-add &> /dev/null; ssh-add ~/.ssh/deploy_key &> /dev/null; fi'
